# Generated by Django 5.0.2 on 2024-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
